

Person.delete_all
State.delete_all
State.create(name:'Alabama', abbreviation: 'AL', capital: 'Montgomery')
State.create(name:'Alaska', abbreviation: 'AK', capital: 'Juneau')
State.create(name:'Arizona', abbreviation: 'AZ', capital: 'Phoenix')
State.create(name:'Arkansas', abbreviation: 'AR', capital: 'Little Rock')
State.create(name:'California', abbreviation: 'CA', capital: 'Sacramento')
State.create(name:'Colorado', abbreviation: 'CO', capital: 'Denver')
State.create(name:'Connecticut', abbreviation: 'CT', capital: 'Hartford')
State.create(name:'Delaware', abbreviation: 'DE', capital: 'Dover')
State.create(name:'Florida', abbreviation: 'FL', capital: 'Tallahassee')
State.create(name:'Georgia', abbreviation: 'GA', capital: 'Atlanta')
State.create(name:'Hawaii', abbreviation: 'HI', capital: 'Honolulu')
State.create(name:'Idaho', abbreviation: 'ID', capital: 'Boise')
State.create(name:'Illinois', abbreviation: 'IL', capital: 'Springfield')
State.create(name:'Indiana', abbreviation: 'IN', capital: 'Indianapolis')
State.create(name:'Iowa', abbreviation: 'IA', capital: 'Des Moines')
State.create(name:'Kansas', abbreviation: 'KS', capital: 'Topeka')
State.create(name:'Kentucky', abbreviation: 'KY', capital: 'Frankfort')
State.create(name:'Louisiana', abbreviation: 'LA', capital: 'Baton Rouge')
State.create(name:'Maine', abbreviation: 'ME', capital: 'Augusta')
State.create(name:'Maryland', abbreviation: 'MD', capital: 'Annapolis')
State.create(name:'Massachusetts', abbreviation: 'MA', capital: 'Boston')
State.create(name:'Michigan', abbreviation: 'MI', capital: 'Lansing')
State.create(name:'Minnesota', abbreviation: 'MN', capital: 'St. Paul')
State.create(name:'Mississippi', abbreviation: 'MS', capital: 'Jackson')
State.create(name:'Missouri', abbreviation: 'MO', capital: 'Jefferson City')
State.create(name:'Montana', abbreviation: 'MT', capital: 'Helena')
State.create(name:'Nebraska', abbreviation: 'NE', capital: 'Lincoln')
State.create(name:'Nevada', abbreviation: 'NV', capital: 'Carson City')
State.create(name:'New Hampshire', abbreviation: 'NH', capital: 'Concord')
State.create(name:'New Jersey', abbreviation: 'NJ', capital: 'Trenton')
State.create(name:'New Mexico', abbreviation: 'NM', capital: 'Santa Fe')
State.create(name:'New York', abbreviation: 'NY', capital: 'Albany')
State.create(name:'North Carolina', abbreviation: 'NC', capital: 'Raleigh')
State.create(name:'North Dakota', abbreviation: 'ND', capital: 'Bismarck')
State.create(name:'Ohio', abbreviation: 'OH', capital: 'Columbus')
State.create(name:'Oklahoma', abbreviation: 'OK', capital: 'Oklahoma City')
State.create(name:'Oregon', abbreviation: 'OR', capital: 'Salem')
State.create(name:'Pennsylvania', abbreviation: 'PA', capital: 'Harrisburg')
State.create(name:'Rhode Island', abbreviation: 'RI', capital: 'Providence')
State.create(name:'South Carolina', abbreviation: 'SC', capital: 'Columbia')
State.create(name:'South Dakota', abbreviation: 'SD', capital: 'Pierre')
State.create(name:'Tennessee', abbreviation: 'TN', capital: 'Nashville')
State.create(name:'Texas', abbreviation: 'TX', capital: 'Austin')
State.create(name:'Utah', abbreviation: 'UT', capital: 'Salt Lake City')
State.create(name:'Vermont', abbreviation: 'VT', capital: 'Montpelier')
State.create(name:'Virginia', abbreviation: 'VA', capital: 'Richmond')
State.create(name:'Washington', abbreviation: 'WA', capital: 'Olympia')
State.create(name:'West Virginia', abbreviation: 'WV', capital: 'Charleston')
State.create(name:'Wisconsin', abbreviation: 'WI', capital: 'Madison')
State.create(name:'Wyoming', abbreviation: 'WY', capital: 'Cheyenne')